- type: entity
  parent: ClothingOuterBaseMedium
  id: SecurityCorps
  name: Корпус Службы Безопасности
  suffix: QAI
  description: бронированный корпус андройда службы безопасности, в котором не только отсутствуют ограничители особых деталей андройда, но и имеется сносная броня для несения службы по охране правопорядка.
  components:
  - type: Item
    size: Huge
    shape:
    - 0,0,2,2
  - type: Storage
    maxItemSize: Huge
    grid:
    - 0,0,4,3
  - type: ContainerContainer
    containers:
      storagebase: !type:Container
        ents: []
  - type: UserInterface
    interfaces:
      enum.StorageUiKey.Key:
        type: StorageBoundUserInterface
  - type: Sprite
    sprite: Imperial/QAIAndroid/clothing/Security.rsi
  - type: Clothing
    sprite: Imperial/QAIAndroid/clothing/Security.rsi
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.55
        Slash: 0.55
        Piercing: 0.5
        Heat: 0.7
        Stamina: 0.7
        Explosion: 0.4
  - type: ClothingSpeedModifier
    walkModifier: 0.9
    sprintModifier: 0.9
